# Generated by Django 3.1.7 on 2021-02-22 15:32

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_auto_20210125_1907"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="movies.movie",
                verbose_name="фильм",
            ),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="movies.movie",
                verbose_name="фильм",
            ),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="movies.reviews",
                verbose_name="Родитель",
            ),
        ),
    ]
